name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "What happened?"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Explain the steps to reproduce the behavior.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened instead.
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS and version info (example: macOS 14.4, Intune Buddy 1.2.3)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Screenshots or logs
      description: Add screenshots or logs if you can.
    validations:
      required: false
